efault: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: shubham       # Change this to your PostgreSQL username
  password: '1234' # Ensure to set your database password in an environment variable
  host: localhost         # Change if your PostgreSQL server is hosted elsewhere

development:
  <<: *default
  database: airbnb_development

test:
  <<: *default
  database: airbnb_test

production:
  <<: *default
  database: airbnb_production
  # Add additional production settings if needed (e.g., username, password)

  